// Mocks generated by Mockito 5.3.2 from annotations
// in asset_vantage/test/src/domain/usecases/cash_balance/cash_balance_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:asset_vantage/src/domain/entities/app_error.dart' as _i5;
import 'package:asset_vantage/src/domain/entities/cash_balance/cash_balance_entity.dart'
    as _i12;
import 'package:asset_vantage/src/domain/entities/cash_balance/cash_balance_grouping_entity.dart'
    as _i6;
import 'package:asset_vantage/src/domain/entities/cash_balance/cash_balance_sub_grouping_entity.dart'
    as _i9;
import 'package:asset_vantage/src/domain/params/cash_balance/cash_balance_report_params.dart'
    as _i13;
import 'package:asset_vantage/src/domain/params/cash_balance/cash_balance_sub_grouping_params.dart'
    as _i10;
import 'package:asset_vantage/src/domain/params/no_params.dart' as _i7;
import 'package:asset_vantage/src/domain/usecases/cash_balance/cash_balance_filters/primary_grouping/get_cash_balance_grouping.dart'
    as _i3;
import 'package:asset_vantage/src/domain/usecases/cash_balance/get_cash_balance_report.dart'
    as _i11;
import 'package:asset_vantage/src/domain/usecases/cash_balance/cash_balance_filters/sub_grouping/get_cash_balance_sub_grouping.dart'
    as _i8;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetCashBalanceGrouping].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCashBalanceGrouping extends _i1.Mock
    implements _i3.GetCashBalanceGrouping {
  MockGetCashBalanceGrouping() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AppError, _i6.CashBalanceGroupingEntity>> call(
          _i7.NoParams? noParams) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [noParams],
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.AppError, _i6.CashBalanceGroupingEntity>>.value(
            _FakeEither_0<_i5.AppError, _i6.CashBalanceGroupingEntity>(
          this,
          Invocation.method(
            #call,
            [noParams],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppError, _i6.CashBalanceGroupingEntity>>);
}

/// A class which mocks [GetCashBalanceSubGrouping].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCashBalanceSubGrouping extends _i1.Mock
    implements _i8.GetCashBalanceSubGrouping {
  MockGetCashBalanceSubGrouping() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AppError, _i9.CashBalanceSubGroupingEntity>> call(
          _i10.CashBalanceSubGroupingParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.AppError,
                    _i9.CashBalanceSubGroupingEntity>>.value(
            _FakeEither_0<_i5.AppError, _i9.CashBalanceSubGroupingEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4
          .Future<_i2.Either<_i5.AppError, _i9.CashBalanceSubGroupingEntity>>);
}

/// A class which mocks [GetCashBalanceReport].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCashBalanceReport extends _i1.Mock
    implements _i11.GetCashBalanceReport {
  MockGetCashBalanceReport() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AppError, _i12.CashBalanceReportEntity>> call(
          _i13.CashBalanceReportParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.AppError, _i12.CashBalanceReportEntity>>.value(
            _FakeEither_0<_i5.AppError, _i12.CashBalanceReportEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppError, _i12.CashBalanceReportEntity>>);
}
