// Mocks generated by Mockito 5.3.2 from annotations
// in asset_vantage/test/src/domain/usecases/preferences/user_preference_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:asset_vantage/src/data/models/preferences/user_preference.dart'
    as _i6;
import 'package:asset_vantage/src/domain/entities/app_error.dart' as _i5;
import 'package:asset_vantage/src/domain/params/no_params.dart' as _i7;
import 'package:asset_vantage/src/domain/params/preference/user_preference_params.dart'
    as _i9;
import 'package:asset_vantage/src/domain/usecases/preferences/get_user_preference.dart'
    as _i3;
import 'package:asset_vantage/src/domain/usecases/preferences/save_user_preference.dart'
    as _i8;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetUserPreference].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserPreference extends _i1.Mock implements _i3.GetUserPreference {
  MockGetUserPreference() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AppError, _i6.UserPreference>> call(
          _i7.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.AppError, _i6.UserPreference>>.value(
                _FakeEither_0<_i5.AppError, _i6.UserPreference>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppError, _i6.UserPreference>>);
}

/// A class which mocks [SaveUserPreference].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveUserPreference extends _i1.Mock
    implements _i8.SaveUserPreference {
  MockSaveUserPreference() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AppError, void>> call(
          _i9.UserPreferenceParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.AppError, void>>.value(
            _FakeEither_0<_i5.AppError, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppError, void>>);
}
