// Mocks generated by Mockito 5.3.2 from annotations
// in asset_vantage/test/src/domain/usecases/net_worth/net_worth_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:asset_vantage/src/domain/entities/app_error.dart' as _i5;
import 'package:asset_vantage/src/domain/entities/net_worth/net_worth_entity.dart'
    as _i18;
import 'package:asset_vantage/src/domain/entities/net_worth/net_worth_grouping_entity.dart'
    as _i6;
import 'package:asset_vantage/src/domain/entities/net_worth/net_worth_number_of_period_entity.dart'
    as _i9;
import 'package:asset_vantage/src/domain/entities/net_worth/net_worth_period_entity.dart'
    as _i12;
import 'package:asset_vantage/src/domain/entities/net_worth/net_worth_sub_grouping_enity.dart'
    as _i15;
import 'package:asset_vantage/src/domain/params/net_worth/net_worth_number_or_period_params.dart'
    as _i10;
import 'package:asset_vantage/src/domain/params/net_worth/net_worth_period_params.dart'
    as _i13;
import 'package:asset_vantage/src/domain/params/net_worth/net_worth_report_params.dart'
    as _i19;
import 'package:asset_vantage/src/domain/params/net_worth/net_worth_sub_grouping_param.dart'
    as _i16;
import 'package:asset_vantage/src/domain/params/no_params.dart' as _i7;
import 'package:asset_vantage/src/domain/usecases/net_worth/get_net_worth_grouping.dart'
    as _i3;
import 'package:asset_vantage/src/domain/usecases/net_worth/get_net_worth_number_of%20_period.dart'
    as _i8;
import 'package:asset_vantage/src/domain/usecases/net_worth/get_net_worth_period.dart'
    as _i11;
import 'package:asset_vantage/src/domain/usecases/net_worth/get_net_worth_report.dart'
    as _i17;
import 'package:asset_vantage/src/domain/usecases/net_worth/get_net_worth_sub_grouping.dart'
    as _i14;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetNetWorthGrouping].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNetWorthGrouping extends _i1.Mock
    implements _i3.GetNetWorthGrouping {
  MockGetNetWorthGrouping() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AppError, _i6.NetWorthGroupingEntity>> call(
          _i7.NoParams? noParams) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [noParams],
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.AppError, _i6.NetWorthGroupingEntity>>.value(
            _FakeEither_0<_i5.AppError, _i6.NetWorthGroupingEntity>(
          this,
          Invocation.method(
            #call,
            [noParams],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppError, _i6.NetWorthGroupingEntity>>);
}

/// A class which mocks [GetNetWorthNumberOfPeriod].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNetWorthNumberOfPeriod extends _i1.Mock
    implements _i8.GetNetWorthNumberOfPeriod {
  MockGetNetWorthNumberOfPeriod() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AppError, _i9.NetWorthNumberOfPeriodEntity>> call(
          _i10.NetWorthNumberOfPeriodParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.AppError,
                    _i9.NetWorthNumberOfPeriodEntity>>.value(
            _FakeEither_0<_i5.AppError, _i9.NetWorthNumberOfPeriodEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4
          .Future<_i2.Either<_i5.AppError, _i9.NetWorthNumberOfPeriodEntity>>);
}

/// A class which mocks [GetNetWorthPeriod].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNetWorthPeriod extends _i1.Mock implements _i11.GetNetWorthPeriod {
  MockGetNetWorthPeriod() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AppError, _i12.NetWorthPeriodEntity>> call(
          _i13.NetWorthPeriodParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.AppError, _i12.NetWorthPeriodEntity>>.value(
            _FakeEither_0<_i5.AppError, _i12.NetWorthPeriodEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppError, _i12.NetWorthPeriodEntity>>);
}

/// A class which mocks [GetNetWorthSubGrouping].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNetWorthSubGrouping extends _i1.Mock
    implements _i14.GetNetWorthSubGrouping {
  MockGetNetWorthSubGrouping() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AppError, _i15.NetWorthSubGroupingEntity>> call(
          _i16.NetWorthSubGroupingParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.AppError, _i15.NetWorthSubGroupingEntity>>.value(
            _FakeEither_0<_i5.AppError, _i15.NetWorthSubGroupingEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4
          .Future<_i2.Either<_i5.AppError, _i15.NetWorthSubGroupingEntity>>);
}

/// A class which mocks [GetNetWorthReport].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNetWorthReport extends _i1.Mock implements _i17.GetNetWorthReport {
  MockGetNetWorthReport() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AppError, _i18.NetWorthReportEntity>> call(
          _i19.NetWorthReportParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.AppError, _i18.NetWorthReportEntity>>.value(
            _FakeEither_0<_i5.AppError, _i18.NetWorthReportEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppError, _i18.NetWorthReportEntity>>);
}
